# Google Cloud Build configuration for automated deployment
# This file defines the build and deployment pipeline

steps:
  # Step 1: Build the Docker container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/whatsapp-ai-assistant:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/whatsapp-ai-assistant:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/whatsapp-ai-assistant:$COMMIT_SHA'
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/whatsapp-ai-assistant:latest'
    id: 'push-image-latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'whatsapp-ai-assistant'
      - '--image'
      - 'gcr.io/$PROJECT_ID/whatsapp-ai-assistant:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'ENV=production,DEBUG=false,LOG_LEVEL=INFO'
    id: 'deploy-cloud-run'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/whatsapp-ai-assistant:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/whatsapp-ai-assistant:latest'

# Build timeout
timeout: '1200s'

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
